// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE7MkhAk4Oeapt3hCmpAxowYoF73lNmxA',
    appId: '1:486390977982:web:10aae74ad3c62e853655ef',
    messagingSenderId: '486390977982',
    projectId: 'flutter-shop-app-58767',
    authDomain: 'flutter-shop-app-58767.firebaseapp.com',
    storageBucket: 'flutter-shop-app-58767.appspot.com',
    measurementId: 'G-S4EP9KE3RS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsTRvDehKA6coCkYPEHof-8wtm100kIrk',
    appId: '1:486390977982:android:9e80707b537d61b33655ef',
    messagingSenderId: '486390977982',
    projectId: 'flutter-shop-app-58767',
    storageBucket: 'flutter-shop-app-58767.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3aT8DTtGXrnsBUmlGaaxrnYQI6SjnOIM',
    appId: '1:486390977982:ios:10613e3c69b4fdf13655ef',
    messagingSenderId: '486390977982',
    projectId: 'flutter-shop-app-58767',
    storageBucket: 'flutter-shop-app-58767.appspot.com',
    iosClientId: '486390977982-ep0sk9ivg7rhmn5kh3a0g4rsccmqmcrq.apps.googleusercontent.com',
    iosBundleId: 'cls',
  );
}
